### ISSUE TITLE
App crashes immediately upon Launching

### ISSUE THREAD

**Issue by theBull** [codefoster/codeshow#12]
I've followed [this link](http://aka.ms/codeshowapp) to install the codeshow app. I'm running Windows 10 on Parallels for Mac OS Sierra (10.12.3) and the *App crashes immediately upon Launch*.

I've also tried cloning the repository, installing the missing SDKs, and an unhandled app exception (unable to start a connection) error is thrown that causes the app to crash when Deploying directly from Visual Studio 2015 as well.

In both cases (install via Windows store, or deploy via cloned project in Visual Studio), I see the interface, followed by a connection exception, followed by the app completely closing. Is anyone maintaining this app anymore?? I'm working on course 70-480 and it'd be very helpful if I could use the app to follow along with the examples.

Is there anything else I can do on my end? I appreciate the help!

**Comment by sebagomez** [comment]
Hello @theBull , unfortunately this app was created for the Windows 8 SDK and has not being updated. 
Having said that, will try to find some time off to see what's missing from running on the Win10 SDK.

**Comment by theBull** [comment]
Thanks! Closing out for now.
