### ISSUE TITLE
Getting Runtime Error on Selectors demo

### ISSUE THREAD

**Issue by Sherryj55** [codefoster/codeshow#2]
When I try to run the Selectors demo, I'm getting
Exception is about to be caught by JavaScript library code at line 6, column 13 in ms-appx://36805codefoster.codeshow/demos/selectors/selectors.js
0x800a138f - JavaScript runtime error: Object expected

Code - last line is where it breaks .....  
(function () {
    "use strict";

```
WinJS.UI.Pages.define("/demos/selectors/selectors.html", {
    ready: function (element, options) {
        q(".selectors #render").innerHTML = q(".selectors pre").innerText;
```

**Comment by sebagomez** [comment]
Hello @Sherryj55 , there is a bug in that sample. 
codeShow is currently work in progress :)

**Comment by Sherryj55** [comment]
Sebastian,

  The screen is now appearing but it’s rendering super wide columns – my screen shows the CSS and HTML boxes but they stretch way past my screen and to see the Render box I have to scroll way over to the right.

**Comment by sebagomez** [comment]
Are you working on the Windows or Windows Phone app?
That sample has not been optimized for Windows Phone yet

**Comment by Sherryj55** [comment]
Hi Sebastian,

  Let me give you some background. I’ve been a .net developer for over 10 years doing mostly Asp .Net and a little Windows development. I have just started studying for my Microsoft certification (MCSD) so have been going through the videos on MVA. So, I set up a virtual machine running Win 8.1 and installed VS 2012 on it and then wanted to play with codeshow as they used in the demos. I then installed VS2013 and followed the instructions on Github to clone the codeshow project. So I just cloned it and ran it in debug and went to the Selectors demo. The solution is showing codeShow.JS.Windows as the start up project.

Sherry

**Comment by sebagomez** [comment]
Hi @Sherryj55 , in that case I would strongly recommend installing the latest published version of the codeShow app from the [store](http://aka.ms/codeshowapp)
You will still be able to take a look at the source of every demo. We're currently working on improving that app with more samples and integrating Windows Phone through the Universal Apps, but I'm sure the app from the store will be of a lot of help. 
I know it was for me :)
